### ISSUE TITLE
Kurulum hatası

### ISSUE THREAD

**Issue by omerbeden** [hacknbreak/2017-scadajs-workshop#3]
Merhaba,
Ben Install kısmında  yarn  # or `npm install`  yazdıktan sonra " warning Error running install script for optional dependency: " gibi bir hata alıyorum "info This module is OPTIONAL, you can safely ignore this error" felan yazıyor sonra burayı geçiyorum  gulp --webapp showcase  dedikten sonra GULP INFO: preparserify : related documents should be an array:
undefined
gibi bir hata alıyorum burda takılıyorum.

**Comment by ceremcem** [comment]
Sisteminizle ilgili bilgi verir misiniz: 

* Hangi işletim sistemi 
* Hangi işlemci mimarisi (32bit/64bit)

Ayrıca komut satırında olan biteni [kod](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) şeklinde yazarak gönderirseniz problemi anlamaya çalışabiliriz.

**Comment by omerbeden** [comment]
Windows 10 64 bit


Omer@Omer-Bilgisayar MINGW64 ~
$ git init myproject
Initialized empty Git repository in C:/Users/Ömer/myproject/.git/

Omer@Omer-Bilgisayar MINGW64 ~
$ cd myproject

Omer@Omer-Bilgisayar MINGW64 ~/myproject (master)
$ git clone https://github.com/aktos-io/scadajs-template myproject
Cloning into 'myproject'...
remote: Counting objects: 198, done.
remote: Compressing objects: 100% (121/121), done.
Receiviremote: Total 198 (delta 74), reused 197 (delta 73), pack-reused 0
Receiving objects: 100% (198/198), 323.15 KiB | 441.00 KiB/s, done.
Resolving deltas: 100% (74/74), done.

Omer@Omer-Bilgisayar MINGW64 ~/myproject (master)
$ git submodule update --init --recursive

Omer@Omer-Bilgisayar MINGW64 ~/myproject (master)
$ cd scada.js
bash: cd: scada.js: No such file or directory

Omer@Omer-Bilgisayar MINGW64 ~/myproject (master)
$ git submodule add https://github.com//aktos-io/scada.js
Cloning into 'C:/Users/Ömer/myproject/scada.js'...
remote: Counting objects: 18263, done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 18263 (delta 65), reused 99 (delta 38), pack-reused 18116
Receiving objects: 100% (18263/18263), 11.18 MiB | 1.48 MiB/s, done.
Resolving deltas: 100% (10173/10173), done.
warning: LF will be replaced by CRLF in .gitmodules.
The file will have its original line endings in your working directory.

Omer@Omer-Bilgisayar MINGW64 ~/myproject (master)
$ git submodule update --init --recursive
Submodule 'src/lib/aktos-dcs' (https://github.com/aktos-io/aktos-dcs-node) registered for path 'scada.js/src/lib/dcs'
Submodule 'tools/service-runner' (https://github.com/aktos-io/service-runner) registered for path 'scada.js/tools/service-runner'
Cloning into 'C:/Users/Ömer/myproject/scada.js/src/lib/dcs'...
Cloning into 'C:/Users/Ömer/myproject/scada.js/tools/service-runner'...
Submodule path 'scada.js/src/lib/dcs': checked out '6443ac7507e92ce0e286c455c258a9c60d48c0a2'
Submodule 'aktos-dcs-design' (https://github.com/aktos-io/aktos-dcs-design) registered for path 'scada.js/src/lib/dcs/aktos-dcs-design'
Submodule 'protocols/siemens/nodeS7' (https://github.com/plcpeople/nodeS7) registered for path 'scada.js/src/lib/dcs/protocols/siemens/nodeS7'
Cloning into 'C:/Users/Ömer/myproject/scada.js/src/lib/dcs/aktos-dcs-design'...
Cloning into 'C:/Users/Ömer/myproject/scada.js/src/lib/dcs/protocols/siemens/nodeS7'...
Submodule path 'scada.js/src/lib/dcs/aktos-dcs-design': checked out '37ec8c236dc52f7ff2ad34fdc63ebccaaa652d23'
Submodule path 'scada.js/src/lib/dcs/protocols/siemens/nodeS7': checked out '95db45c4ae1e9864fc165b7f398143c5687e5a38'
Submodule path 'scada.js/tools/service-runner': checked out '0e62afcf5362a14e2f66b934d1f883a569d35226'

Omer@Omer-Bilgisayar MINGW64 ~/myproject (master)
$ cd scada.js

Omer@Omer-Bilgisayar MINGW64 ~/myproject/scada.js (master)
$ yarn # or `npm install`
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
warning fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning Error running install script for optional dependency: "C:\\Users\\Ömer\\myproject\\scada.js\\node_modules\\ursa: Command failed.\nExit code: 1\nCommand: C:\\WINDOWS\\system32\\cmd.exe\nArguments: /d /s /c node-gyp rebuild\nDirectory: C:\\Users\\Ömer\\myproject\\scada.js\\node_modules\\ursa\nOutput:\nC:\\Users\\�mer\\myproject\\scada.js\\node_modules\\ursa>if not defined npm_config_node_gyp (node \"C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\node-gyp-bin\\\\..\\..\\node_modules\\node-gyp\\bin\\node-gyp.js\" rebuild )  else (node \"\" rebuild ) \r\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@6.11.2 | win32 | x64\ngyp ERR! configure error \ngyp ERR! stack Error: Can't find Python executable \"python\", you can set the PYTHON env variable.\ngyp ERR! stack     at failNoPython (C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:449:14)\ngyp ERR! stack     at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\lib\\configure.js:404:11\ngyp ERR! stack     at C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\graceful-fs\\polyfills.js:264:29\ngyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)\ngyp ERR! System Windows_NT 10.0.14393\ngyp ERR! command \"C:\\\\Program Files\\\\nodejs\\\\node.exe\" \"C:\\\\Program Files\\\\nodejs\\\\node_modules\\\\npm\\\\node_modules\\\\node-gyp\\\\bin\\\\node-gyp.js\" \"rebuild\"\ngyp ERR! cwd C:\\Users\\Ömer\\myproject\\scada.js\\node_modules\\ursa\ngyp ERR! node -v v6.11.2\ngyp ERR! node-gyp -v v3.4.0\ngyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
Done in 231.55s.

Omer@Omer-Bilgisayar MINGW64 ~/myproject/scada.js (master)
$ gulp --webapp showcase
[02:28:10] Requiring external module livescript
------------------------------------------
Webapp  : showcase
------------------------------------------
[02:28:13] Using gulpfile ~\myproject\scada.js\gulpfile.ls
[02:28:13] Starting 'default'...
[02:28:13] Starting 'browserify'...
[02:28:13] Starting 'html'...
[02:28:13] Starting 'vendor-js'...
[02:28:13] Starting 'vendor-css'...
[02:28:13] Starting 'assets'...
[02:28:13] Starting 'pug'...
[02:28:13] Starting 'preparserify-workaround'...
[02:28:13] Finished 'html' after 75 ms
[02:28:13] Finished 'pug' after 50 ms
GULP INFO: browserify : Browserify finished (showcase)
------------------------------------------
[02:28:13] Finished 'browserify' after 348 ms
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
[02:28:20] Finished 'vendor-js' after 7.48 s
GULP INFO: preparserify : related documents should be an array:
undefined
GULP INFO: preparserify : related documents should be an array:
undefined
[02:28:20] Finished 'preparserify-workaround' after 7.56 s
[02:28:21] Finished 'assets' after 7.87 s
[02:28:22] Finished 'vendor-css' after 8.93 s

**Comment by ceremcem** [comment]
### Tespit 

Öncelikle iki ayrı README birbirine karıştırılmış gibi duruyor. `cd scada.js` komutu çalışmıyor, çünkü başta bir `myproject` oluşturduktan sonra `scadajs-template`i onun içine klonlamışsınız. Dolayısıyla siz aslında `scadajs-template`i es geçip kendinize sıfırdan bir ScadaJS projesi oluşturmaya kalkmışsınız, ancak bu noktada da `webapps` klasörü (ve onun içeriği) olmadığı için hata almışsınız.

### Çözüm

Tam olarak [buradaki](https://github.com/aktos-io/scadajs-template#install) adımları izler misiniz?

**Comment by omerbeden** [comment]
teşekkür ederim  browser da açıldı :)


17 Ağustos 2017 02:59 tarihinde Cerem Cem ASLAN <notifications@github.com>
yazdı:

**Comment by ceremcem** [comment]
Rica ederim.
